// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return $.getJSON('./Posts/posts.txt', function(postData) {
      var closeActive, element, getFullElementHeight, openPost, openUrl, post, _i, _len;
      for (_i = 0, _len = postData.length; _i < _len; _i++) {
        post = postData[_i];
        element = $("<article><h1>" + post.Title + "</h1><div id='guts'></div></article>");
        $('#content').append(element);
        element.data('post', "" + post.Title);
        element.data('postUrl', "http://02credits.com/Posts/" + post.Url + "/post.html");
        element.data('url', post.Url);
      }
      $('article').on('transitionend', function() {
        var guts;
        if ($(this).hasClass('active')) {
          guts = $(this).find('#guts');
          guts.addClass('noTransitions');
          guts.css('height', 'auto');
          return setTimeout(function() {
            return guts.removeClass('noTransitions');
          }, 20);
        }
      });
      $('article > h1').bind('click', function(e) {
        var article, open;
        article = $(this).parent();
        open = !article.hasClass('active');
        closeActive();
        if (open) {
          openPost(article);
          return history.pushState(null, null, 'http://02credits.com/' + article.data('url'));
        } else {
          return history.pushState(null, null, 'http://02credits.com/');
        }
      });
      openPost = function(article) {
        var guts, postUrl, url;
        postUrl = article.data('postUrl');
        url = article.data('url');
        guts = article.find('#guts');
        return guts.load(postUrl, function() {
          var height, tmp;
          article.addClass('active');
          tmp = guts.clone();
          tmp.css({
            'height': 'auto'
          });
          tmp.appendTo(guts.parent());
          height = tmp.outerHeight();
          tmp.remove();
          return guts.css('height', height);
        });
      };
      closeActive = function() {
        return $('.active').each(function() {
          var article, guts, height;
          article = $(this);
          guts = article.find('#guts');
          guts.addClass('noTransitions');
          height = getFullElementHeight(guts);
          guts.css('height', height);
          return setTimeout(function() {
            guts.removeClass('noTransitions');
            guts.css('height', 0);
            return article.removeClass('active');
          }, 20);
        });
      };
      getFullElementHeight = function(element) {
        var height, tmp;
        tmp = element.clone();
        tmp.appendTo(element.parent());
        tmp.css('height', 'auto');
        height = tmp.outerHeight();
        tmp.remove();
        return height;
      };
      openUrl = function() {
        var article, newUrl;
        closeActive();
        newUrl = location.pathname.replace(/^.*[\\/]/, '');
        if (newUrl !== '') {
          article = $('article').filter(function() {
            var url;
            url = $(this).data('url').toLowerCase();
            return url === newUrl.toLowerCase();
          });
          if (article.length > 0) {
            return openPost(article);
          }
        }
      };
      openUrl();
      return $(window).bind('popstate', function() {
        return openUrl();
      });
    });
  });

}).call(this);
