import "./errorLogger"
import "./chatCommands"
import "./emoticons"
import "./plugins"
import "./messageRenderer"
import "./messagesManager"
import "./scrollManager"
import "./uiSetup"
import "./inputManager"
import "./idleManager"
import "./settings"
import "./fileCache"
import "./fileManager"
import "./markov"
import "./materialize.scss"
import "./style.sass"

window.baseTitle = "Bonfire"
